spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:h2:mem:wallet-db
  docker:
    compose:
      enabled: false
  cloud:
    config:
      discovery:
        enabled: false
      enabled: false
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: walletEvent:net.tanguydev.walletservice.Domain.Events.WalletEvent
    consumer:
      group-id: wallet-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
eureka:
  client:
    enabled: false
server:
  port: 8083
