spring:
  application:
    name: gateway-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          default-filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/digipay
          jwk-set-uri: http://localhost:8080/realms/digipay/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

gateway:
  params:
    connect-timeout-ms: 3000
    response-timeout-ms: 5000

server:
  port: 8888

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: customer-service
        url: /customer-service/v3/api-docs
      - name: wallet-service
        url: /wallet-service/v3/api-docs
      - name: payment-service
        url: /payment-service/v3/api-docs
      - name: fraud-service
        url: /fraud-service/v3/api-docs
      - name: notification-service
        url: /notification-service/v3/api-docs
      - name: settlement-service
        url: /settlement-service/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
